### PR TITLE
Adding Power support(ppc64le) with continuous integration/testing so that project stays architecture independent.

### PR DESCRIPTION
**Pull request by asellappen**
Please review and merge the changes ,This is part of the Ubuntu distribution for ppc64le.
This helps us simplify testing later when distributions are re-building and re-releasing. For more info tag @gerrith3.

### CODE REVIEW

**Comment by akavel** [comment]
I don't understand the purpose of this PR, can you please explain it better to me? Until that, I'm marking this as invalid [[1]](https://hacktoberfest.digitalocean.com/details#spam).

**Comment by asellappen** [comment]
Hi Gerrit,
This PR has been put under invalid as Mateusz Czapliński is expecting more explanation for the PR, Can you please paas more inputs ?
https://github.com/akavel/rsrc/pull/31


Thanks &RegardsN S Arumugam.

    On Tuesday, October 6, 2020, 10:48:23 PM GMT+5:30, Mateusz Czapliński <notifications@github.com> wrote:  
 
 


I don't understand the purpose of this PR, can you please explain it better to me? Until that, I'm marking this as invalid [1].

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Add poweron architecture ppc64le to travis build by asellappen · Pull Re...

Please review and merge the changes ,This is part of the Ubuntu distribution for ppc64le. This helps us simplify...
 |

 |

 |

**Comment by gerrith3** [comment]
@asellappen no need to quote the entire email - all of that info is in the thread here.  ;)  

@akavel I realize this is/should be a pure go implementation but 1) there is a small chance of a deviation in go itself between Intel and ppc64le.  Not likely, but not ideal.  Being able to catch any projects which do have a difference as early as possible is a good thing.  Second, we have found go projects which use assembly level call outs for optimization or reaches out to fixed location intel based binaries to supplement their work.  View this is a simple sweep to catch either of those cases.  They should be rare/unlikely (but also so should be any defects in general ;-)  but since the resources are free, the work to do the testing is all included here, and the time to do the testing is free/run in parallel by Travis, there shouldn't be any downsides to this patch.

**Comment by asellappen** [comment]
@akavel ,Hope the above clarification would be sufficient and pls  let us know if you need further,

**Comment by asellappen** [comment]
@akavel ,,any update on this request ?

**Comment by akavel** [comment]
@gerrith3 the original submission contained wording: "This is part of the Ubuntu distribution for ppc64le." - what is "This" meaning there? Also, can you please give some proof as to this statement ("part of the Ubuntu distribution for ppc64le") - e.g. some link that could convince me this is true? Also, are you planning to check somehow if the builds passed before distributing, or is it intended only to softly warn me that I might be breaking your stuff? Sorry for the hassle, but given "hacktober", weird and low effort PRs out of the blue, esp. with crappy grammar & wording, unfortunately require much more scrutiny and the proof's burden is on the authors at this time.

**Comment by gerrith3** [comment]
@akavel is this what you are looking for?  You can also look at the Ubuntu Universe manifest and probably at Debian as well.

```
ubuntu@gerrit:~$ sudo apt-cache search rsrc
golang-github-akavel-rsrc-dev - Go library for embedding binary resources in executables
ubuntu@gerrit:~$ uname -a
Linux gerrit 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:33 UTC 2020 ppc64le ppc64le ppc64le GNU/Linux
```

**Comment by gerrith3** [comment]
And btw, that is a stock Linux install, no additional repositories added.

**Comment by akavel** [comment]
As to what I'm looking for, I'd really be grateful for some link on the internet on the Ubuntu website where I could verify this. You seem to mention an "Ubuntu Universe manifest" - I don't know what it is, but if it's something viewable on the internets on ubuntu website, is there a chance you might point me with a link to where rsrc shows up in it? You seem to be familiar with it, so you might be able to generate such a link much easier than if I started to research what "Ubuntu Universe manifest" is.

Unfortunately, "hacktober" is a difficult month for contributions (as I explained above), and this contribution was started in a super low quality way, giving the air of the worst hacktober offenders (believe me, I've seen my number of them). Since then I haven't seen any "hard proof" in this thread, that would be difficult to fake. However hacktober is slowly waning away in the past, the dust is starting to settle, and you at least use grammar & interpunction which soothes my nerves. So I extended my good will and assumed there's nonzero chance you might be up to something, so for as long as this doesn't seem to impediment me, [I added the target to Travis in meantime](https://github.com/akavel/rsrc/blob/67980f0b8b9acfb9cc862afe75fd47ce5325cc54/.travis.yml#L18-L21). I took care to try and do it in a way that would make sure this PR won't count to "hacktober".

A question that I asked in the previous comment that you still didn't answer, is: 
> Also, are you planning to check somehow if the builds passed before distributing, or is it intended only to softly warn me that I might be breaking your stuff? 

That question is related specifically to your mention about:
>  Being able to catch any projects which do have a difference as early as possible [...]

I'd like to understand in what way you (?) are "catching any projects which do have a difference"? And how you observe "a difference"?

**Pull request closed without merging**
